### ISSUE TITLE
Same here better remove this line and variable 

### ISSUE THREAD

**Issue by carlos-gil** [lao-tseu-is-alive/go-cloud-k8s-thing#2]
https://github.com/lao-tseu-is-alive/go-cloud-k8s-object/blob/ab5678975c46b3ff15b428e9936f3863ee80e2ac/Dockerfile#L46

**Comment by lao-tseu-is-alive** [comment]
Ok good idea
Will remove it

**Comment by lao-tseu-is-alive** [comment]
Fixed in latest commit
